spring:
  security:
    oauth2:
      client:
        registration:
          gitlab:
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8080/login/oauth2/code/gitlab'
            client-id: gitlab-client-id  #Need to get the Client-ID
            client-secret : gitlab-client-secret #Need to get the Client Secret
            scope : openid , read_user
            provider : gitlab
            client-authentication-method:
        provider :
          gitlab :
            authorization-uri: https://gitlab.com/oauth/authorizeF
            token-uri : https :// gitlab .com/oauth/token
            user-info-uri: https://gitlab.com/oauth/userinfo
            jwk-set-uri: https://gitlab.com/oauth/discovery/keys
logging :
level :
org :
  springframework :
  security: DEBUG
